; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
build_flags =
	-DCONFIG_XPOWERS_ESP_IDF_NEW_API
	-DPIN_NB_DTR=42
	-DI2C_SDA_0=15
	-DI2C_SCL_0=7
	-DMODEM_TXD_PIN=5
	-DMODEM_RXD_PIN=4
	-DMODEM_DTR_PIN=42
	-DMODEM_PWRKEY_PIN=41
	-DMODEM_PWRKEY_PULSE_MS=1200
	-DMODEM_WAKE_INTERVAL_SEC=59
	-DLOW_BATTERY_ENTER_MV=3600
	-DLOW_BATTERY_RECOVER_MV=3800
	-DLOW_BATTERY_CHECK_INTERVAL_SEC=1200
	-DMODEM_APN=\"lpwa.vodafone.com\"
	-DCOAP_SERVER=\"example.coap.com\"
	-DCOAP_PORT=5683
	-DCOAP_PATH=\"/meteo-1234\"
	-DCOAP_PUBLISH_TIMEOUT_SEC=20
lib_deps =
	lewisxhe/XPowersLib@^0.3.2
	https://github.com/m-mcgowan/pio-ulp-cmake.git
extra_scripts =
	pre:${PROJECT_LIBDEPS_DIR}/${PIOENV}/pio-ulp-cmake/scripts/pio_ulp_cmake.py
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.ulp_projects =
	ulp_main:ulp
